import { Inter } from "next/font/google";
import "../globals.css";
import Navigation from "../component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full min-h-screen">
        <Navigation/>
        { children }
        </main>
      </body>
    </html>
  );
}
